##### Websocket API #####
ProgressTrackingWebsocket:
  Type: AWS::ApiGatewayV2::Api
  Properties:
    Name: ProgressTrackingWebsocketApi
    ProtocolType: WEBSOCKET
    RouteSelectionExpression: "$request.body.action"
ConnectRoute:
  Type: AWS::ApiGatewayV2::Route
  Properties:
    ApiId: !Ref ProgressTrackingWebsocket
    RouteKey: $connect
    AuthorizationType: NONE
    OperationName: ConnectRoute
    Target: !Join ["/", ["integrations", !Ref ConnectInteg]]
ConnectInteg:
  Type: AWS::ApiGatewayV2::Integration
  Properties:
    ApiId: !Ref ProgressTrackingWebsocket
    Description: Connect Integration
    IntegrationType: AWS_PROXY
    IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations
DisconnectRoute:
  Type: AWS::ApiGatewayV2::Route
  Properties:
    ApiId: !Ref ProgressTrackingWebsocket
    RouteKey: $disconnect
    AuthorizationType: NONE
    OperationName: DisconnectRoute
    Target: !Join ["/", ["integrations", !Ref DisconnectInteg]]
DisconnectInteg:
  Type: AWS::ApiGatewayV2::Integration
  Properties:
    ApiId: !Ref ProgressTrackingWebsocket
    Description: Disconnect Integration
    IntegrationType: AWS_PROXY
    IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations
OrderRoute:
  Type: AWS::ApiGatewayV2::Route
  Properties:
    ApiId: !Ref ProgressTrackingWebsocket
    RouteKey: onOrder
    AuthorizationType: NONE
    OperationName: OrderingRoute
    Target: !Join ["/", ["integrations", !Ref OrderInteg]]
OrderInteg:
  Type: AWS::ApiGatewayV2::Integration
  Properties:
    ApiId: !Ref ProgressTrackingWebsocket
    Description: Ordering Integration
    IntegrationType: AWS_PROXY
    IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnOrderFunction.Arn}/invocations
Deployment:
  Type: AWS::ApiGatewayV2::Deployment
  DependsOn:
    - ConnectRoute
    - DisconnectRoute
    - OrderRoute
  Properties:
    ApiId: !Ref ProgressTrackingWebsocket
Stage:
  Type: AWS::ApiGatewayV2::Stage
  Properties:
    StageName: !Ref ApiStageName
    Description: Prod Stage
    DeploymentId: !Ref Deployment
    ApiId: !Ref ProgressTrackingWebsocket
