version = 0.1
[default.deploy.parameters]
stack_name = "cammy-demo"
resolve_s3 = true
s3_prefix = "cammy-demo"
region = "eu-west-2"
profile = "personal"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiStageName=\"Prod\""
image_repositories = []
